/* ═══════════════════════════════════════════════════════════
   QuantumEAR — Supabase Client
   ═══════════════════════════════════════════════════════════ */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = supabaseUrl && supabaseAnonKey
    ? createClient(supabaseUrl, supabaseAnonKey)
    : null;

/**
 * Save scan result to Supabase
 */
export async function saveScanToSupabase(scan: {
    id: string;
    filename: string;
    trust_score: number;
    label: string;
    processing_time_ms: number;
    timestamp: string;
}) {
    if (!supabase) {
        console.log('Supabase not configured — scan saved locally only');
        return null;
    }

    const { data, error } = await supabase
        .from('scan_history')
        .insert([{
            scan_id: scan.id,
            filename: scan.filename,
            trust_score: scan.trust_score,
            label: scan.label,
            processing_time_ms: scan.processing_time_ms,
            scanned_at: scan.timestamp,
        }]);

    if (error) {
        console.error('Supabase save error:', error);
        return null;
    }

    return data;
}

/**
 * Get scan history from Supabase
 */
export async function getHistoryFromSupabase(limit: number = 50) {
    if (!supabase) return [];

    const { data, error } = await supabase
        .from('scan_history')
        .select('*')
        .order('scanned_at', { ascending: false })
        .limit(limit);

    if (error) {
        console.error('Supabase fetch error:', error);
        return [];
    }

    return data || [];
}

/**
 * SQL migration for creating the scan_history table in Supabase.
 * Run this in the Supabase SQL editor.
 */
export const SUPABASE_MIGRATION = `
-- QuantumEAR Scan History Table
CREATE TABLE IF NOT EXISTS scan_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id UUID NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  trust_score DECIMAL(5,1) NOT NULL,
  label TEXT NOT NULL CHECK (label IN ('organic', 'synthetic')),
  processing_time_ms DECIMAL(10,1),
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_scan_history_scanned_at ON scan_history(scanned_at DESC);
CREATE INDEX IF NOT EXISTS idx_scan_history_label ON scan_history(label);

-- Row Level Security
ALTER TABLE scan_history ENABLE ROW LEVEL SECURITY;

-- Allow all operations for now (configure auth later)
CREATE POLICY "Allow all" ON scan_history FOR ALL USING (true);
`;
