-- QuantumEAR Database Schema for Supabase
-- Run this SQL in the Supabase SQL Editor

-- Scan History Table
CREATE TABLE IF NOT EXISTS scan_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id UUID NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  trust_score DECIMAL(5,1) NOT NULL,
  label TEXT NOT NULL CHECK (label IN ('organic', 'synthetic')),
  synthetic_probability DECIMAL(6,4),
  processing_time_ms DECIMAL(10,1),
  entropy_regions_count INTEGER DEFAULT 0,
  quantum_features JSONB,
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_scan_history_scanned_at ON scan_history(scanned_at DESC);
CREATE INDEX IF NOT EXISTS idx_scan_history_label ON scan_history(label);
CREATE INDEX IF NOT EXISTS idx_scan_history_trust_score ON scan_history(trust_score);

-- Row Level Security
ALTER TABLE scan_history ENABLE ROW LEVEL SECURITY;

-- Public read/write policy (configure auth for production)
CREATE POLICY "Allow all operations" ON scan_history
  FOR ALL USING (true) WITH CHECK (true);

-- Function to get scan statistics
CREATE OR REPLACE FUNCTION get_scan_stats()
RETURNS TABLE(
  total_scans BIGINT,
  organic_count BIGINT,
  synthetic_count BIGINT,
  avg_trust_score DECIMAL,
  avg_processing_time DECIMAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT,
    COUNT(*) FILTER (WHERE label = 'organic')::BIGINT,
    COUNT(*) FILTER (WHERE label = 'synthetic')::BIGINT,
    ROUND(AVG(trust_score), 1),
    ROUND(AVG(processing_time_ms), 1)
  FROM scan_history;
END;
$$ LANGUAGE plpgsql;
